In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    "Name" : ["Jhon","anna","peter","Linda"],
    "Age": [28,34,29,42],
    "City":["New York","Paris","Berlin","London"],
    "Salary":[65000,70000,62000,85000]
}
labels= ["a","b","c","d"]

In [3]:
df =pd.DataFrame(data,index =labels)

In [4]:
df

    Name  Age      City  Salary
a   Jhon   28  New York   65000
b   anna   34     Paris   70000
c  peter   29    Berlin   62000
d  Linda   42    London   85000

In [5]:
data_list = [
    ["Jhon" ,28,"New York",65000],
    ["Anna",34,"Paris",70000],
    ["Peter",29,"Berlin",62000],
    ["Linda",42,"London",850000]
]
labels= ["a","b","c","d"]
columns = ["Name","Age","City","Salary"]

df2=pd.DataFrame(data_list,columns = columns)

In [6]:
df2

    Name  Age      City  Salary
0   Jhon   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London  850000

**Selection and Indexing columns**

In [7]:
df2

    Name  Age      City  Salary
0   Jhon   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London  850000

In [8]:
df2[["Name","City"]]

    Name      City
0   Jhon  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

**Creating a new colum**

In [9]:
df2["Designation"] = ["Doctor","Engineer","Doctor",'Engineer']

In [10]:
df2

    Name  Age      City  Salary Designation
0   Jhon   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London  850000    Engineer

**Remove columns**

In [11]:
df2.drop("Designation",axis =1,inplace =True)
df2

    Name  Age      City  Salary
0   Jhon   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London  850000

**Selecting rows**

In [12]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  Jhon   28  New York   65000
1  Anna   34     Paris   70000

In [13]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary    850000
Name: 3, dtype: object

**Selecting subset of rows and columns**

In [14]:
df2.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [15]:
df2

    Name  Age      City  Salary
0   Jhon   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London  850000

In [16]:
df2.loc[[2,0]][["Name","Age"]]

    Name  Age
2  Peter   29
0   Jhon   28

**Conditional Selection**

In [17]:
df2

    Name  Age      City  Salary
0   Jhon   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London  850000

In [18]:
# Want to see poeple whoes age is above 30  # mversion
a=df2["Age"]
b=a>30

df2[b]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London  850000

In [19]:
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London  850000

I only want people whose age is above 30 and their city must be paris

In [20]:
df2[(df2["Age"]>30) & (df2["City"]== "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000